In [1]:
import numpy as np

In [2]:
lista=[1,2,3,4,5] #Lista en Python

In [10]:
lista[0] #para obtener un valor en una lista de Python

1

In [5]:
listaNumpy=np.array([1,2,3,4,5])

In [7]:
 listaNumpy2D=np.array([[1,2,3],[4,5,6]]) # lista en 2D
 listaNumpy2D

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
#matriz de ceros
listaNumpyZeros = np.zeros((3,4))
listaNumpyZeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
for i in listaNumpy:
  print(i*i)

1
4
9
16
25


In [14]:
len(listaNumpy) #tamaño nunpy

5

In [18]:
listaNumpyZeros.shape[0] # tamaño en matriz en numpy

3

In [21]:
for i in range(listaNumpyZeros.shape[0]):
  print(listaNumpyZeros[i][0])

0.0
0.0
0.0


In [22]:
#Sumas en numpy
print(listaNumpy.sum())

15


In [25]:
#media en numpy
print(listaNumpy.mean())

3.0


In [26]:
transpuesta= np.transpose(listaNumpy2D)
transpuesta

array([[1, 4],
       [2, 5],
       [3, 6]])

In [28]:
#mediana
mediana= np.median(listaNumpy)
mediana

3.0

In [ ]:
# PANDAS

In [30]:
import pandas as pd

In [34]:
df=pd.DataFrame{"NombreAutos":["Audi","Toyota","Ford","Lamborghini"],"kilometraje":[1000,0,45000,9000]})

In [35]:
df

NombreAutos  kilometraje
0         Audi         1000
1       Toyota            0
2         Ford        45000
3  Lamborghini         9000

In [36]:
valores=[1,2,3,4]
rayos=["gama","beta","x","y"]
df2=pd.DataFrame({"Varlor":valores,"rayos":rayos})

In [37]:
df2

Varlor rayos
0       1  gama
1       2  beta
2       3     x
3       4     y

In [44]:
array=df2[:1].to_numpy()
array

array([[1, 'gama']], dtype=object)

In [45]:
df2.to_numpy()

array([[1, 'gama'],
       [2, 'beta'],
       [3, 'x'],
       [4, 'y']], dtype=object)

In [47]:
data = {'Product': ['ABC','DDD','XYZ','AAA','CCC','PPP','NNN','RRR'],
          'Price': [630,790,250,370,880,1250,550,700],
       'Discount': ['No','Yes','No','Yes','Yes','No','No','Yes']
        }

In [55]:
df3= pd.DataFrame(data,columns=['Product','Price','Discount'])

In [56]:
df3

Product  Price Discount
0     ABC    630       No
1     DDD    790      Yes
2     XYZ    250       No
3     AAA    370      Yes
4     CCC    880      Yes
5     PPP   1250       No
6     NNN    550       No
7     RRR    700      Yes

In [58]:
datesPrice= df3[0:1]
datesPrice

Product  Price Discount
0     ABC    630       No

In [63]:
df3.columns.values # nombres  de nuestras columnas

array(['Product', 'Price', 'Discount'], dtype=object)

In [67]:
datasPriceColum= df3['Price']
priceNumpy=datasPriceColum.to_numpy()
priceNumpy

array([ 630,  790,  250,  370,  880, 1250,  550,  700])

In [68]:
promedioPrice= priceNumpy.mean()
promedioPrice

677.5

In [ ]:
pd.read_excel("archivo.xsl")